<h2>Administrative Staff</h2>

<p>Administrative Supervisors To keep SUA running, administrative supervisors oversee various areas of operation within the organization. These indivduals oversee and organize things such as member training, special events and facility requirements.Administrative supervisors are elected to their position every year and devote time to ensure that SUA continues to run smoothly.</p>
<div id="memberbox">
    <h5>Alec Massood <span style='float:right'>Personnel&nbsp;&nbsp;</span></h5>
</div>
<div id="memberbox">
    <h5>Carrie Stith <span style='float:right'>Personnel&nbsp;&nbsp;</span></h5>
</div>
<div id="memberbox">
    <h5>Andy Ades <span style='float:right'>Fleet&nbsp;&nbsp;</span></h5>
</div>
<div id="memberbox">
    <h5>Josue Deya <span style='float:right'>Facilities&nbsp;&nbsp;</span></h5>
</div>
<div id="memberbox">
    <h5>Eric Merrell <span style='float:right'>Events&nbsp;&nbsp;</span></h5>
</div>
<div id="memberbox">
    <h5>Lily Kim <span style='float:right'>Training&nbsp;&nbsp;</span></h5>
</div>