<h2>Faculty</h2>
       	<p>To ensure that SUA can continue to be a service available on campus, full-time staff members work tirelessly to ensure training, operations and procedures are taught and followed properly. These individuals oversee and maintain the organization and it's members.</p>
        	
        	
			<div id="memberbox"><h5>Paul Smyth<span style='float:right'>EMS Manager&nbsp;&nbsp;</span></h5></div>
			<div id="memberbox"><h5>Kathleen Linnertz<span style='float:right'>Communications&nbsp;&nbsp;</span></h5></div>

			<br /><br/>
<h3>Health Services Faculty</h3>
<p>In addition to the faculty members directly responsible for overseeing SUA's operations, the organization would not exist without the continued involvement and support of the administrative staff of Syracuse University's Health Services department. </p>

			<div id="memberbox"><h5>Dr. Spiro Tzetzis<span style='float:right'>Medical Director&nbsp;&nbsp;</span></h5></div>
			<div id="memberbox"><h5>Benjamin Domingo<span style='float:right'>Director&nbsp;&nbsp;</span></h5></div>
			<!--
			<div id="memberbox"><h5>Palma Cassano <span style='float:right'>Business Manager&nbsp;&nbsp;</span></h5></div>
			<div id="memberbox"><h5>Donna McLaughlin <span style='float:right'>Office Manager&nbsp;&nbsp;</span></h5></div>
			<div id="memberbox"><h5>Kathy Shattuck<span style='float:right'>Administration&nbsp;&nbsp;</span></h5></div>
			<div id="memberbox"><h5>Kathy Van Vechten<span style='float:right'>Special Assistant to the Director&nbsp;&nbsp;</span></h5></div>
-->
