<h2>Officers</h2>

<p>Being run almost entirely by students, SUA is a Student Association recognized organization. Because of this, SUA receives financial aid from the SA operations budget and helps to ensure that emergency services remain free for students, faculty and staff. SUA maintains a group of elected individuals who act as liaisons for the organization during Student Association meetings or events.</p>
<div id="memberbox">
    <h5>Eric Harris <span style='float:right'>President&nbsp;&nbsp;</span></h5>
</div>
<div id="memberbox">
    <h5>Sean Lamble <span style='float:right'>Vice President&nbsp;&nbsp;</span></h5>
</div>
<div id="memberbox">
    <h5>Shannon Salem <span style='float:right'>Treasurer&nbsp;&nbsp;</span></h5>
</div>
<div id="memberbox">
    <h5>Emma Rivard <span style='float:right'>Secretary&nbsp;&nbsp;</span></h5>
</div>