<h2>Probationary Members</h2>
<p>Congratulations to our Spring 2014 probationary class for their new acceptance into SUA. <!--Their names are now listed on our <a href="roster.php?type=active">Active Members page</a>.--> We are continually accepting applications for new members, and review applications twice per year. We encourage all interested to apply online! 

       <!--	<p>Each semester, SUA holds an open application process to recruit new members. This year was exceptionally difficult as over 100 applicants were competing for only 14 spots. We are extremely grateful for the interest we received and encourage those interested in SUA to consider applying again in the future. </p> -->
       	
       <!--	<p>The following members have been accepted into SUA's Spring 2012 probationary class. Over the next few weeks, these individuals will learn the basics of working for an ambulance corp and receive basic life support training. At the end of their probationary period, these members will demonstrate their skills in a testing environment before being welcomed as full-time members. </p> -->


        	
<table width="600" border="0" cellspacing="1" cellpadding="1">
<tr>
<td width="296">Conor Campbell</td>
<td width="297">Josue Deya</td>
</tr>
<tr>
  <td>Ben Freedman</td>
  <td width="297">Emily Griffin</td>
  </tr>
<tr>
  <td>Erin Hurley</td>
  <td>Alec Massood</td>
  </tr>
<tr>
  <td>Lukas Moller</td>
  <td>Ian Molloy</td>
  </tr>
<tr>
  <td>			
Caroline Morba</td>
  <td>Emma Rivard</td>
  </tr>
<tr>
  <td>Mike Solomon</td>
  <td>Carrie Stith</td>
  </tr>
<tr>
  <td>Mehdi Teymouri</td>
  <td>Christian Zinone</td>
  </tr>
</table>














