<h2>SUA Banquet 2011</h2>
<hr />


    <iframe src="https://player.vimeo.com/video/41264498" width="940" height="529" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe> <p><a href="https://vimeo.com/41264498">SUA Banquet 2012</a> from <a href="https://vimeo.com/sua">Syracuse University Ambulance</a> on <a href="https://vimeo.com">Vimeo</a>.</p> <p>Created by Jaime Bernstein, Steph Kranz, Lexi Kivari, Molly Westbrook &amp; Matt Smith<br /> <br /> Special thanks to Will O&#039;Donnell, Kathryn Dewar and Paul Smyth</p>   
    <br />
