<h2>SUA Banquet 2011</h2>
<hr />


    <iframe src="https://player.vimeo.com/video/92165389" width="940" height="529" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe> <p><a href="https://vimeo.com/92165389">SUA Banquet 2014</a> from <a href="https://vimeo.com/sua">Syracuse University Ambulance</a> on <a href="https://vimeo.com">Vimeo</a>.</p> <p>Created by Luke Rafferty and the 2014 SUA Banquet Committee.<br /> Special thanks to Paul Smyth and the 2013-2014 Field Supervisors.</p>   <br />
