<h2>SUA Banquet 2011</h2>
<hr />


    <iframe src="https://player.vimeo.com/video/64107338" width="940" height="529" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe> <p><a href="https://vimeo.com/64107338">SUA Banquet 2013</a> from <a href="https://vimeo.com/sua">Syracuse University Ambulance</a> on <a href="https://vimeo.com">Vimeo</a>.</p> <p>Created by Kathryn Dewar, Jared Mandel and the 2013 SUA Banquet Committee.<br /> Special thanks to Paul Smyth and the 2012-2013 Field Supervisors.</p> 
    <br />
