<h2>First Aid / Basic Life Support</h2>
<p>If you are interested in receiving training in first aid and basic life support, classes are taught each semester by SUA personnel.  </p>


<h4>No classes are currently available. Please check back soon.</h4>
<!-- <h3>General Information</h3>
<p>The EMT-B original certification course is held once during the fall academic semester and once in the spring. Additionally, a class is also offered during the summer. The class runs Mondays and Wednesdays from 6:00PM to 9:30PM. Additionally, you are required to attend practical skill days on some Saturdays from 9:00AM to 4:30PM. </p>

<h3>Cost of Attendance</h3>
<p>The total cost of the class is $804.00. (This includes the $699.00 for tuition and $105.00 for required textbooks). </p>

<h3>Location</h3>
<p>Unless otherwise specified, the class is held at the Rural/Metro Medical Services station at 488 West Onondaga Street in Syracuse, NY.</p>-->

   <!-- <div align="center"><a class="large button orange" href="start.php"><span>Ready? Click Here To Get Started!</span></a></div>    -->              
