<h2>CPR Certification</h2>
<p>If you are interested in becoming certified (or renewing your existing certification) in CPR, AHA-approved classes are taught by CPR instructors from SUA regularly throughout the year.  </p>

<div align="center"><img src="images/cpr.jpg" /></div>

<br />

<hr />


<h4>No classes are currently available. Please check back soon.</h4>
<h3>Hands-Only CPR Certification</h3>

<!-- <p>Hand-only CPR classes will be offered during Health & Wellness week on April 22, 2014. Classes will be held each hour from 10:00AM to 4:00PM. Each class will have a 25 person capacity.</p>
<p>A night class will also be offered at 6:00PM with a 50 person capacity</p>
<p>If you are interested in singing up, please fill out the form below.</p> -->


<!-- <div id="wufoo-mdfhucb1wo78h3">
Fill out my <a href="https://sua.wufoo.com/forms/mdfhucb1wo78h3">online form</a>.
</div>-->
<div id="wuf-adv" style="font-family:inherit;font-size: small;color:#a7a7a7;text-align:center;display:block;">HTML Forms powered by <a href="http://www.wufoo.com">Wufoo</a>.</div>
<script type="text/javascript">var mdfhucb1wo78h3;(function(d, t) {
var s = d.createElement(t), options = {
'userName':'sua',
'formHash':'mdfhucb1wo78h3',
'autoResize':true,
'height':'703',
'async':true,
'host':'wufoo.com',
'header':'show',
'ssl':true};
s.src = ('https:' == d.location.protocol ? 'https://' : 'http://') + 'wufoo.com/scripts/embed/form.js';
s.onload = s.onreadystatechange = function() {
var rs = this.readyState; if (rs) if (rs != 'complete') if (rs != 'loaded') return;
try { mdfhucb1wo78h3 = new WufooForm();mdfhucb1wo78h3.initialize(options);mdfhucb1wo78h3.display(); } catch (e) {}};
var scr = d.getElementsByTagName(t)[0], par = scr.parentNode; par.insertBefore(s, scr);
})(document, 'script');</script>



<!-- <h3>General Information</h3>
<p>The EMT-B original certification course is held once during the fall academic semester and once in the spring. Additionally, a class is also offered during the summer. The class runs Mondays and Wednesdays from 6:00PM to 9:30PM. Additionally, you are required to attend practical skill days on some Saturdays from 9:00AM to 4:30PM. </p>

<h3>Cost of Attendance</h3>
<p>The total cost of the class is $804.00. (This includes the $699.00 for tuition and $105.00 for required textbooks). </p>

<h3>Location</h3>
<p>Unless otherwise specified, the class is held at the Rural/Metro Medical Services station at 488 West Onondaga Street in Syracuse, NY.</p>-->

   <!-- <div align="center"><a class="large button orange" href="start.php"><span>Ready? Click Here To Get Started!</span></a></div>    -->              
