<h2>Become an Emergency Medical Technician</h2>
<p>If you are interested in becoming certified as a New York State Emergency Medical Technician (NYS EMT-B), a publicly available course is sponsored by Rural Metro Medical Services. </p>

<h3>General Information</h3>
<p>The next available EMT-B original certification class will be held this spring from <strong>January 20, 2014</strong> to <strong>May, 2014</strong>. The program rums from 6:30PM to 9:30PM on Monday and Wednesday nights and some Saturday classes will be held from 9:00AM to 4:00PM as needed.</p>

<h3>Cost of Attendance</h3>
<p>The total cost of the class is $945.00. (This includes the $790.00 for tuition and $155.00 for required textbooks). </p>

<h3>Location</h3>
<p>Unless otherwise specified, the class is held at the Rural/Metro Medical Services station at 488 West Onondaga Street in Syracuse, NY.</p>

<p class="small">Please note: Space is extremely limited and students are accepted on a first come, first serve basis. If you are interested in taking the class, please complete your application as soon as possible. </p>

   <div align="center"><a class="large button orange" href="files/EMTSpring2015.pdf"><span>Download Application (PDF)</span></a></div>                  
