<ul>
  <li><a href="http://people.alfred.edu/~aurs/" target="_blank">Alfred University Rescue Squad</a></li>
  <li><a href="http://student.bard.edu/clubs/ems/" target="_blank">Bard EMS</a></li>
  <li><a href="http://www.brooklyn.cuny.edu/web/about/offices/studentaffairs/offices/ems.php" target="_blank">Brooklyn College Emergency Medical Squad</a></li>
  <li><a href="http://www.cuems.org/" target="_blank">Columbia University EMS</a></li>
  <li><a href="http://cuems.cornell.edu/" target="_blank">Cornell University EMS</a></li>
  <li><a href="http://www.fordham.edu/campus_resources/student_services/fordham_university_e/" target="_blank">Fordham University EMS</a></li>
  <li><a href="http://hcems.hamilton.edu/" target="_blank">Hamilton College EMS</a></li>
  <li><a href="http://www.liu.edu/CWPost/About/Offices/Public-Safety/Emergency-Mgmt/EMS.aspx" target="_blank">Long Island University (CW Post) EMS</a></li>
  <li><a href="http://ambulance.union.rpi.edu/" target="_blank">Rensselaer Polytechnic Institute Ambulance Agency</a></li>
  <li><a href="http://apps.rit.edu/studentaffairs/studenthealth/rita/" target="_blank">Rochester Institute of Technology Ambulance</a></li>
  <li><a href="http://www.stlawu.edu/ems/" target="_blank">St. Lawrence University EMS</a></li>
  <li><a href="http://www.fivequad.org/" target="_blank">SUNY Albany Five Quad Volunteer Ambulance</a></li>
  <li><a href="http://www.geneseo.edu/~esquad/" target="_blank">SUNY Cortland Emergency Squad</a></li>
  <li><a href="http://organizations.oneonta.edu/oses/OSES-NEW/" target="_blank">SUNY Oneonta Emergency Squad</a></li>
  <li><a href="http://www.savacambulance.org/" target="_blank">SUNY Oswego Student Association VAC</a></li>
  <li><a href="http://www.potsdamcrs.com/main.php" target="_blank">SUNY Potsdam Campus Rescue Squad</a></li>
  <li><a href="http://www.sbvac.org/" target="_blank">SUNY Stony Brook VAC</a></li>
  <li><a href="http://www.security.rochester.edu/mert/" target="_blank">University of Rochester Medical ERT</a></li>
  <li><a href="http://vsa.vassar.edu/orgs/vcems/" target="_blank">Vassar College EMS</a></li>
</ul>