
<h3>7/31/11 - Version 3.0 GM</h3>
<table width="620" border="0" cellspacing="1" cellpadding="5">
  <tr>
    <td width="597"><ul>
      <li>Code freeze</li>
      <li>Bug fixes</li>
      <li>File performance optimization</li>
      <li>Link checking</li>
    </ul></td>
  </tr>
</table>
<h3>&nbsp;</h3>
<h3>7/31/11 - Version 3.0 RC2</h3>
<table width="620" border="0" cellspacing="1" cellpadding="5">
  <tr>
    <td width="597"><ul>
      <li>Fixed link color/hover issues</li>
      <li>Added images to about page sections</li>
      <li>Added patch logo to about page</li>
      <li>Added vehicle galleries to photo system</li>
      <li>Added information to community outreach section</li>
    </ul></td>
  </tr>
</table>
<h3>&nbsp;</h3>
<h3>7/31/11 - Version 3.0 RC1</h3>

<table width="620" border="0" cellspacing="1" cellpadding="5">

  <tr>

    <td width="597"><ul>

      <li>Added links to about page content</li>

      <li>Revised MTS policy information on transport page</li>

      <li>Revised University department links</li>

      <li>Uploaded new photo galleries</li>

      <li>Added application information and button to homepage</li>

      <li>Revised structure chart</li>

      <li>Fixed an issue with header displaying too large on Mobile Safari</li>

    </ul></td>

  </tr>

</table>

<h3>&nbsp;</h3>
<h3>7/27/11 - Version 3.0b6</h3>

<table width="620" border="0" cellspacing="1" cellpadding="5">

  <tr>

    <td width="597"><ul>

      <li>Finalized application system and process</li>

      <li>Added SUA and MTS eSchedule links to footers</li>

      <li>Moved footer page to includes area (for consistency across all pages)</li>

      <li>Added photo gallery sections</li>

      <li>Added vehicle photos and rotating links</li>

    </ul></td>

  </tr>

</table>

<h3>&nbsp;</h3>
<h3>7/24/11 - Version 3.0b5</h3>



<table width="620" border="0" cellspacing="1" cellpadding="5">



  <tr>



    <td width="597"><ul>



      <li>Added color to emergency pop-up link when hovering</li>



	  <li>Fixed links within application system</li>



	  <li>Added informational pages to application system</li>



	  <li>New left footer area with rotating content</li>



    </ul></td>



  </tr>



</table>







<br />







<!-- START 3.0b4 -->







<h3>&nbsp;</h3>
<h3>7/24/11 - Version 3.0b4</h3>



<table width="620" border="0" cellspacing="1" cellpadding="5">



  <tr>



    <td width="597"><ul>



      <li>Added titles to all pages</li>



      <li>Fixed link destinations in sidebars</li>



      <li>Added photos to gallery</li>



      <li>New video pages</li>



      <li>Fixed list of dispatch trainers</li>



      <li>Added videos page to menu</li>



      <li>Resolved issue with vehicle pages</li>



    </ul></td>



  </tr>



</table>







<br />







<!-- START 3.0b3 -->











<h3>&nbsp;</h3>
<h3>7/18/11 - Version 3.0b3</h3>







<table width="620" border="0" cellspacing="1" cellpadding="5">







  <tr>







    <td width="597"><ul>







      <li>Minor display fixes.  </li>







    </ul></td>







  </tr>







</table>















<br />















<!-- START 3.0b2 -->

<h3>&nbsp;</h3>
<h3>7/17/11 - Version 3.0b2</h3>







<table width="620" border="0" cellspacing="1" cellpadding="5">







  <tr>







    <td width="597"><ul>







      <li>Fixed links to department websites. </li>







      <li>Deployed FAQ page framework. </li>







      <li>Fixed photo gallery .CSS files. </li>







      <li>Added images to recognition.php page</li>







    </ul></td>







  </tr>







</table>















<br />















<!-- START 3.0b1 -->







<h3>&nbsp;</h3>
<h3>7/15/11 - Version 3.0b1</h3>







<table width="620" border="0" cellspacing="1" cellpadding="5">







  <tr>







    <td width="597"><ul>







      <li>Initial beta release. </li>







      <li>Beta flags added to index pages linking to bug report submission form. </li>







      <li>Site content moved from development server to deployment server. </li>







      <li>Twitter API added to allow tweets to be properly displayed. </li>







      <li>Photos added to gallery for testing purposes. </li>







    </ul></td>







  </tr>







</table>







