<ul>
  <li><a href="http://counselingcenter.syr.edu/" target="_blank">Counseling Center</a> </li>
  <li><a href="http://fasa.syr.edu/" target="_blank">Fraternity & Sorority Affairs</a></li>
  <li><a href="http://health.syr.edu/" target="_blank">Health Services</a> </li>
  <li><a href="http://studentconduct.syr.edu/" target="_blank">Judicial Affiars</a> </li>
  <li><a href="http://lc.syr.edu/" target="_blank">Learning Communities</a> </li>
  <li><a href="http://oocp.syr.edu/" target="_blank">Off-Campus & Commuter Services</a> </li>
  <li><a href="http://parents.syr.edu/" target="_blank">Parents Office</a> </li>
  <li><a href="http://publicsafety.syr.edu" target="_blank">Public Safety</a></li>
  <li><a href="http://advocacycenter.syr.edu"target="_blank">Advocacy Center</a> </li>
  <li><a href="http://recreationservices.syr.edu/" target="_blank">Recreation Services</a> </li>
  <li><a href="http://orl.syr.edu/" target="_blank">Residence Life</a> </li>
  <li><a href="http://safety.syr.edu" target="_blank">Safety Department</a></li>
  <li><a href="http://studentactivities.syr.edu/" target="_blank">Student Activities</a> </li>
  <li><a href="http://www.syr.edu/currentstudents/studentassistance.html" target="_blank">Student Assistance</a></li>
  <li><a href="http://scps.syr.edu/" target="_blank">Student Centers & Programming Services</a></li>
</ul>