<h2>Dispatchers</h2>
<p>Before an ambulance can be sent to your location, an emergency medical dispatcher is responsible for taking down vital information, assessing the situation and providing pre-arrival medical help over the phone. SUA dispatches all calls "in-house" from our headquarters.</p>

<p>A paid student dispatcher is available to answer the phone and assist you whenever necessary. All dispatchers are trained by dispatch trainers within the organization and are required to take a national certification course to be recognized emergency medical dispatchers.</p>

			<div id="memberbox"><h5>Diana Acebedo <span style='float:right'>Trainer&nbsp;&nbsp;</span></h5></div>
			<div id="memberbox"><h5>Katherine Bunch <span style='float:right'>Trainer&nbsp;&nbsp;</span></h5></div>
			<div id="memberbox"><h5>Andrew Brown <span style='float:right'>Trainer&nbsp;&nbsp;</span></h5></div>
			<div id="memberbox"><h5>Adrian Camaj <span style='float:right'>Trainer&nbsp;&nbsp;</span></h5></div>
			<div id="memberbox"><h5>Matt Davis <span style='float:right'>Progression&nbsp;&nbsp;</span></h5></div>
			<div id="memberbox"><h5>Brendan Dwyer <span style='float:right'>Progression&nbsp;&nbsp;</span></h5></div>
			<div id="memberbox"><h5>Matthew Feibert <span style='float:right'>Trainer&nbsp;&nbsp;</span></h5></div>
			<div id="memberbox"><h5>Austin Hager <span style='float:right'>Progression&nbsp;&nbsp;</span></h5></div>
			<div id="memberbox"><h5>Matt Jean <span style='float:right'>&nbsp;&nbsp;</span></h5></div>
			<div id="memberbox"><h5>Jack Kaczmarczyk <span style='float:right'>Trainer&nbsp;&nbsp;</span></h5></div>
			<div id="memberbox"><h5>Lily Kim <span style='float:right'>Progression&nbsp;&nbsp;</span></h5></div>
			<div id="memberbox"><h5>Sam Lauffer <span style='float:right'>Trainer&nbsp;&nbsp;</span></h5></div>
			<div id="memberbox"><h5>Sean Lamble <span style='float:right'>Progression&nbsp;&nbsp;</span></h5></div>
			<div id="memberbox"><h5>Riley Levy <span style='float:right'>&nbsp;&nbsp;</span></h5></div>
			<div id="memberbox"><h5>Jared Mandel <span style='float:right'>Trainer&nbsp;&nbsp;</span></h5></div>
			<div id="memberbox"><h5>Natale March <span style='float:right'>Trainer&nbsp;&nbsp;</span></h5></div>
			<div id="memberbox"><h5>Alec Massood <span style='float:right'>Progression&nbsp;&nbsp;</span></h5></div>
			<div id="memberbox"><h5>Eric Merrell <span style='float:right'>Progression&nbsp;&nbsp;</span></h5></div>
			<div id="memberbox"><h5>Caroline Morba <span style='float:right'>Progression&nbsp;&nbsp;</span></h5></div>
			<div id="memberbox"><h5>Natalie Montesano <span style='float:right'>Progression&nbsp;&nbsp;</span></h5></div>
			<div id="memberbox"><h5>Luke Rafferty <span style='float:right'>&nbsp;&nbsp;</span></h5></div>
			<div id="memberbox"><h5>Brittany Rodriguez <span style='float:right'>Progression&nbsp;&nbsp;</span></h5></div>
			<div id="memberbox"><h5>Marisa Rodriguez <span style='float:right'>&nbsp;&nbsp;</span></h5></div>
			<div id="memberbox"><h5>Shannon Salem <span style='float:right'>Progression&nbsp;&nbsp;</span></h5></div>
			<div id="memberbox"><h5>A.J. Schramm <span style='float:right'>Progression&nbsp;&nbsp;</span></h5></div>	
			<div id="memberbox"><h5>Hannah Sherman <span style='float:right'>Trainer&nbsp;&nbsp;</span></h5></div>
			<div id="memberbox"><h5>Arielle Steinberg <span style='float:right'>Trainer&nbsp;&nbsp;</span></h5></div>
			<div id="memberbox"><h5>Catherine Stith <span style='float:right'>Progression&nbsp;&nbsp;</span></h5></div>
