	<!-- start footer -->    
	<div id="footer" class="clearfix">
		<div class="container_12">
			<div class="grid_5">
                <div class="widget">
                <!-- Left promo area start -->
				<?php include("includes/footer-left.inc")?>
				</div><!--widget-->
				<!-- Left promo area end -->
            </div><!--//grid_5-->
			<div class="grid_7">
				<div class="widget twitter-widget">
                <h3 class="widgettitle"><small class="right">Follow us <a href="http://twitter.com/suambulance">@suambulance</a></small>Twitter</h3>
                    <div id="latest-footer-tweets"></div>
                    </div>
                <div class="widget">
				<!-- Recent promotions area start -->
				<?php include("promotions.inc")?>
								<!-- Recent promotions area end -->
				</div><!--widget-->
			</div><!--grid_7-->
		</div><!--container-12-->
		<div id="footer-bottom" class="clearfix">
			<div class="container_12">
            	<div class="grid_12" style="padding-top:20px;">
                    <p class="left">&copy; Syracuse University Ambulance</p>
                    <p class="right" >eSchedule: <a href="http://su.emseschedule.com">SUA</a> | <a href="http://sumts.emseschedule.com">MTS</a> | SUA Email: <a href="http://mail.google.com/a/sua.syr.edu">Access</a><!--<a href="#" class="scroll-top" title="Back to the Top">TOP</a>--></p>
                </div>
            </div>
        </div> 
    </div><!--footer-->
</div><!--outer-->
	<script type="text/javascript" src="./js/analytics.js"></script>
	
</body>
</html>            