



                    	<h3 class="widgettitle">In an emergency...</h3>
             		<p>In the event of a medical emergency, <strong>please remain calm.</strong> Call SUA at <strong>(315) 443-4299</strong> and be prepared with some basic information:<br/><br/></p>
             			<ul>
             				<li>- The address of the emergency.</li>
             				<li>- The phone number you're calling from.</li>
             				<li>- Exactly what happened.</li>
             				<li>- How many people are hurt.</li>
             				<li>- If anyone is already helping you.</li>
             			</ul><br/>
             		Follow any and all instructions the dispatcher gives you and <strong>do not hang up until you have been told to do so.</strong></p>

<!--
                    	<h3 class="widgettitle">Apply to SUA!</h3>
             		<p>Interested in becoming a part of one of the best organizations at Syracuse University? We're hiring! <strong>SUA is currently looking for potential members of the Spring 2012 probationary class</strong>. Applications are being accepted from now until September 22nd </p>
             		<br />
             		   					<div align="center"><a class="large button orange" href="join"><span>Ready? Click here to apply to SUA!</span></a>   </div>
             		<br/>
             		<p>If you think you have what it takes to join the ranks and become a member of Syracuse University Ambulance, you can apply now!</p>
             		<br/>


							-->
<!--
                    	<h3 class="widgettitle">Apply to SUA!</h3>
             		<p>Thank you for your interest in Syracuse University Ambulance! Our Fall 2011 application is now closed, but we will begin looking for new members in the Spring! </p>

             		<br/>
             		<p>Now that the online application deadline has passed, we can no longer consider new candidates for this semester. Our selection process takes a number of weeks so we are unable to accept late entries. We sincerely appreciate your interest in SUA and encourage you to apply again in the future! </p>
             		<br/>
-->


<!--
                    	<h3 class="widgettitle">Welcome to SUA!</h3>
             		<p>Earlier this semester, SUA accepted a class of 14 new members to make up the Fall 2011 probationary class. Eight weeks later, these members were put to the test and completed a written and scenario-based exam to become full members. Congratulations to the entire class and the newest group of members tasked with providing EMS coverage to Syracuse University!</p> <br />
             		             		<br />
             	<div align="center"><a class="large button orange" href="news.php"><span>View Fall 2011 New Member Class!</span></a>   </div>
             		<br/> -->


   <!--


             		                    	<h3 class="widgettitle">Awards & Recognition</h3>

		<img src="../images/website-web.png" />

		<img src="../images/advisor-web.png" />
-->
