
                    	<h3 class="widgettitle">In an emergency...</h3>
             		<p>In the event of a medical emergency, <strong>please remain calm.</strong> Call SUA at <strong>(315) 443-4299</strong> and be prepared with some basic information:<br/><br/></p>
             			<ul>
             				<li>- The address of the emergency.</li>
             				<li>- The phone number you're calling from.</li>
             				<li>- Exactly what happened.</li>
             				<li>- How many people are hurt.</li>
             				<li>- If anyone is already helping you.</li>
             			</ul><br/>
             		Follow any and all instructions the dispatcher gives you and <strong>do not hang up until you have been told to do so.</strong></p>

      		             		

<!--
       <h3 class="widgettitle">Recent Promotions</h3>
            <p>Congratulations to the following members for their recent promotions:<br/><br/></p>
             		
             	<div id="memberbox"><p>John Burke <span style='float:right'>CCP&nbsp;&nbsp;</span></p></div>
             	<div id="memberbox"><p>Matthew Smith <span style='float:right'>DRP&nbsp;&nbsp;</span></p></div> 
-->            		             		


