				<ul class="sf-menu">

					<li><a href="index.php">Home</a></li>
					<li><a href="about.php">About</a>
						<ul>
							<!--<li><a href="history.php">History</a></li>-->
							<li><a href="about.php">General</a></li>
							<li><a href="vehicles.php">Vehicles</a></li>
							<li><a href="recognition.php">Recognition</a></li>
							<li><a href="faq.php">FAQs</a></li>
							<li><a href="structure.php">Structure</a></li>	
							<li><a href="services.php">Services</a>
									<ul>
									<li><a href="service.php?type=ambulance">Response</a></li>
									<li><a href="service.php?type=transport">Transport</a></li>
									<li><a href="service.php?type=events">Events</a></li>
									<li><a href="service.php?type=mci">Mass Casualty</a></li>
									</ul>
							</li>	
									
							<li><a href="outreach.php">Outreach</a>
						
								<ul>
								<li><a href="events.php">Upcoming Events</a></li>
								<li><a href="aed.php">AED Locations</a></li>
								<li><a href="event.php?type=emt">EMT Class</a></li>
								<li><a href="event.php?type=cpr">CPR Training</a></li>
								<li><a href="rideout.php">Ride Out Program</a></li>

								</ul>
						</ul>
						
							</li>
							
					<li><a href="members.php">Members</a>
						<ul>
					<li><a href="roster.php?type=active">Active</a></li>
					<li><a href="roster.php?type=supervisors">Supervisors</a></li>
					<!--<li><a href="roster.php?type=probationary">Probationary</a></li>-->
					<li><a href="roster.php?type=officers">Officers</a></li>
					<li><a href="roster.php?type=administrative">Administrative</a></li>
					<li><a href="roster.php?type=dispatch">Dispatchers</a></li>
					<li><a href="roster.php?type=faculty">Faculty</a></li>
							</ul>
					</li>
					<li><a href="news.php">News</a></li>
					<li><a style="cursor:pointer">Media</a>
						<ul>
							<li><a href="press.php">Press</a></li>
							<li><a href="http://instagram.com/suambulance" target="_blank">Photos</a></li>
							<li><a href="videos.php">Videos</a></li>
							<!--<li><a href="downloads.php">Downloads</a></li>-->
						</ul>
					</li>
					<li><a href="contact.php">Contact</a></li>

				</ul>