
<h3 class="widgettitle">Recent Promotions</h3>
<ul>
  <table width="500" border="0">
    <tr>
      <td>Emelia Navarrete</td>
      <td>Driver Progression</td>
    </tr>
	<tr>
      <td>Ilana Siegal</td>
      <td>Driver Progression</td>
    </tr>
	<tr>
      <td>Hamish Gibbs</td>
      <td>Dispatcher</td>
    </tr>
	<tr>
      <td>Brian Kievit</td>
      <td>Dispatcher Progression</td>
    </tr>
  </table>
</ul>
<!-- If No Promotions <p>Sorry, no recent promotions. -->
</div>
