<h2>Emergency Response</h2>
<p>Syracuse University Ambulance responds to over 1,500 medical emergencies each year. SUA is capable of providing intermediate life support, rapid cardiac defibrillation and transport to area hospitals and trauma centers. To provide advanced life support services, SUA has a mutual aid agreement with Rural/Metro Medical Services in the city of Syracuse. When requested, an ALS unit or paramedic fly-car will rendezvous with the ambulance and provide advanced life support interventions on the University ambulance. </p>



<p>SUA operates two full-time BLS-equipped ambulances each compliant with NYS Department of Health regulations. Maintained by our fleet supervisor, these vehicles are available any time day or night to respond to any type of emergency. In addition to two primary ambulances, SUA also operates a supervisor's fly car that acts as a first response vehicle. The on-duty field supervisor will also use this vehicle to respond to critical calls that require additional supervision and oversight or to tow the medical support unit to the scene of a mass casualty incident.</p>

	<img src="images/service-ambulance.jpg" />
	
	<hr />



