<h2>Special Events</h2>
<p>In addition to providing 24/7 emergency campus coverage, SUA is also utilized as a standby medical service at sporting events, concerts, parades, festivals and other public gatherings. Working in conjunction with Carrier Dome Medical teams and athletic trainers, SUA provides services for all major sporting events held at the Carrier Dome. Capable of seating upwards of 50,000 people, SUA is utilized to ensure spectator and player safety. </p>

<p>Syracuse University Ambulance also ensures the safety of participants in large-scale University events. You'll find ambulance crews ready to respond at convocations, commencements, award ceremonies, public speakers and greek events. Additionally, SUA staffs a team of eight foot responders, two ambulances and full MCI mobilization for Syracuse University's "MayFest" event. </p>

<h3>Pricing</h3>
<p>SUA provides flexible staffing that is designed to fit the needs of your event and budget. In general, the following rates apply:

<table width="400" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td>BLS Ambulance</td>
    <td>$87.00/hr.</td>
  </tr>
  <tr>
    <td>EMT Foot Responder</td>
    <td>$43.50/hr.</td>
  </tr>
</table>

<br />

<p>For more information or to speak to someone about having SUA standing by at your next event, <a href="contact.php">click here</a>. </p>

	<img src="images/service-event.jpg" />

	<hr />

