<h2>Mass Casualty Incident Response</h2>
<p>SUA's Mass Casualty Incident trailer is one of the most highly regarded aspects of the agency. SUA is currently one of two agencies within Onondaga County to have MCI response capabilities. Put into service in 1999 and upgraded in 2009, SUA's trailer is outfitted with equipment designed to respond to mutual aid for large or small scale multiple patient catastrophes. Within this trailer there are over 30 backboard setups, MCI tagging equipment, ALS medical support equipment for local ALS agencies, BLS medical support bags/boxes, a backup generator, scene lights, portable oxygen setups for over 30 people and scene organizational equipment.</p>
               		
<p>As a result of SUA's MCI capabilities and equipment, SU Ambulance in conjunction with Onondaga County Fire/EMS/and Police agencies, conducts numerous MCI training programs in an effort to increase large-scale training readiness. These training programs familiarize the agencies and individuals with incident command, usage of equipment, treatment of patients, etc. during large scale MCI's. Working with local area hospitals, large size simulation programs are conducted at Hancock International Airport, the Syracuse Regional Transportation Center, the Carousel Mall Complex, and other strategic training locations.
SUA participates in a yearly MCI drill on campus that involved many agencies including Syracuse Police, DPS, bomb squad units and the FBI.</p>

	<img src="images/service-mci.jpg" />
	
	<hr />



