<h2>Medical Transport</h2>
<p>Syracuse University Medical Transportation Services (MTS) provides non-emergency ambulatory transport for students with temporary mobility impairment and those with permanent mobility impairment whose routine transport is temporarily interrupted. Service is provided on a temporary basis for medically necessary transportation needs. Transports are limited to four one-way transports per day.</p>

<p>MTS operates seven days a week from 7:00 a.m. to 10:00 p.m. From 10:00 p.m. to 7:00 a.m. Limited service is available only for transport from area hospitals and urgent care centers back to residences.MTS is supported by student health fees; there is no out-of-pocket expense during the academic year for students who have paid the fee. There is, however, a charge for non-health fee payers and those requesting service during the summer session.Temporary transport is available for students who will require less than two weeks of service and can be scheduled on an "as needed" basis for campus service and transport to near-campus medical facilities.</p>

<p>Long-term transport is only available for those with a temporary disability requiring more than two weeks of service in the campus and near-campus areas. Long-term medical transport requires a physician’s medical documentation. A scheduling package will be sent to assist students in setting up transport.</p>

<p>MTS answers all medically necessary transportation requests on North Campus, South Campus, ESF Campus and in the near-campus area bordered by Route 81, East Genesee Street, Westcott Street, Meadowbrook Drive, and Ainsley Drive.</a>

<p>**Please Note: Depending on the circumstances, an ambulance may be a more appropriate means for transport to Health Services or an area hospital. The student will be advised if an ambulance is being dispatched.</p>

<h3>Interested in becoming an MTS driver?</h3>
<p>We're always looking for qualified drivers to operate our medical transportation service. If you are interested in applying, <a href="../mts-application.php">click here</a>.</p>

	
	<hr />



